/** Centralised UI copy for UNO. */
export const unoStrings = {
  landing: {
    title: 'UNO',
    subtitle: 'The classic card game — be the first to empty your hand.',
    createLobby: 'Create a room',
    creating: 'Creating…',
    joinLobby: 'Join a room',
    joinDescription: 'Enter a 6-digit room code',
    joinModalTitle: 'Join a room',
    joinCodeLabel: 'Room code',
    joinCodePlaceholder: '123456',
    join: 'Join',
    back: '← Back to games',
    format: 'Match format',
    single: 'Single round',
    singleHint: 'First to empty their hand wins',
    to200: 'First to 200',
    to500: 'First to 500',
    pointsHint: 'Play rounds until someone hits the target',
    mode: 'Game mode',
    modeClassic: 'Classic',
    modeCustom: 'Custom',
    modeNoMercy: 'No Mercy',
    modeFlip: 'Flip',
    modeClassicHint: 'Official 108-card rules. Nothing added.',
    modeCustomHint: 'Classic deck + the house rules you toggle below.',
    modeNoMercyHint: 'Brutal deck (Draw 6/10, Skip Everyone, Discard All). Stack draws; hit 25 cards and you’re OUT. Last player standing wins.',
    modeFlipHint: 'Double-sided deck. A Flip card flips everyone to the Dark side — harsher cards.',
    houseRules: 'House rules',
    stacking: 'Stacking',
    stackingOn: 'On (+2 on +2, +4 on +4)',
    stackingOff: 'Off (official rules)',
    stackingHint: 'House rule — pass draw penalties along the table',
    ruleStacking: 'Stacking (+2 / +4)',
    ruleDrawToMatch: 'Draw to Match',
    ruleJumpIn: 'Jump-In',
    ruleSevenZero: 'Seven-0 (swap / rotate)',
    ruleForcePlay: 'Force Play',
    ruleNoBluffing: 'No Bluffing (+4)',
  },
  hud: {
    yourTurn: 'Your turn',
    waitingFor: (name: string) => `${name}’s turn`,
    draw: 'Draw',
    pass: 'Pass',
    takeCards: (n: number) => `Take +${n}`,
    challenge: 'Challenge',
    playDrawn: 'Play drawn card',
    unoButton: 'UNO!',
    catch: 'Catch!',
    pickColor: 'Pick a colour',
    drawPile: 'Draw pile',
    stackingBadge: 'Stacking',
    spectating: 'Spectating',
    reconnecting: 'Reconnecting…',
    round: (n: number) => `Round ${n}`,
    challengeHint: 'They may have been bluffing…',
    surrender: 'Surrender',
    surrenderTitle: 'Surrender?',
    surrenderBody: 'You’ll be out of this game for good. Are you sure?',
    surrenderYes: 'Yes, quit',
    surrenderNo: 'Keep playing',
    chooseSwap: 'Choose whose hand to take',
    jumpInHint: 'Jump in with an identical card!',
  },
  events: {
    play: (name: string) => `${name} played`,
    draw: (name: string) => `${name} drew a card`,
    skip: (name: string) => `${name} was skipped`,
    reverse: 'Direction reversed',
    uno: (name: string) => `${name} shouted UNO!`,
    caught: (name: string) => `${name} forgot UNO — +2!`,
    challengeWin: 'Challenge won — bluff caught!',
    challengeLoss: 'Challenge failed — +2!',
    take: (name: string, n: number) => `${name} drew ${n}`,
    reshuffle: 'Deck reshuffled',
    colorChange: (color: string) => `Colour is now ${color}`,
    flip: 'FLIP! Everyone turns over',
    swap: (name: string) => `${name} swapped hands`,
    rotate: 'Everyone passed their hand',
    discardAll: (name: string) => `${name} dumped a whole colour`,
    surrender: (name: string) => `${name} surrendered`,
    eliminated: (name: string) => `${name} is OUT — too many cards!`,
  },
  over: {
    roundTitle: 'Round over',
    matchTitle: 'Game over',
    wonRound: (name: string) => `${name} won the round`,
    wonMatch: (name: string) => `${name} wins! 🏆`,
    lastStanding: (name: string) => `${name} is the last one standing! 🏆`,
    points: (n: number) => `+${n} points`,
    nextRound: 'Next round starting…',
    backToLobby: 'Back to lobby',
    playAgain: 'Play again',
  },
  errors: {
    loading: 'Dealing the cards…',
    disconnected: 'Reconnecting…',
    noGame: 'No active UNO game found.',
  },
} as const;
