import { GameType, type GameCatalogEntry } from '../shared';
import { GameRegistry } from './game-registry';

const EXISTING_GAMES: GameCatalogEntry[] = [
  {
    key: 'bingo',
    name: 'Bingo',
    mark: '75',
    description: 'Build your card and race for five lines.',
    route: '/games/bingo',
    accent: '#ff684d',
    surface: '#351d19',
    gameType: GameType.BINGO,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 8,
    modes: [
      { key: 'online', route: '/games/bingo' },
      { key: 'offline', route: '/games/bingo/offline' },
    ],
  },
  {
    key: 'chess',
    name: 'Chess',
    mark: '\u265e',
    description: 'Live clocks, legal moves and classic match play.',
    route: '/games/chess',
    accent: '#65aaf6',
    surface: '#182938',
    gameType: GameType.CHESS,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 2,
    modes: [{ key: 'online', route: '/games/chess' }],
  },
  {
    key: 'ludo',
    name: 'Ludo',
    mark: '\u25cf',
    description: 'Race four tokens around a true 15\u00d715 board.',
    route: '/games/ludo',
    accent: '#63d5a4',
    surface: '#173126',
    gameType: GameType.LUDO,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 4,
    modes: [
      { key: 'online', route: '/games/ludo' },
      { key: 'offline', route: '/games/ludo/offline' },
    ],
  },
  {
    key: 'photobooth',
    name: 'Photobooth',
    mark: '\u25ce',
    description: 'A cozy couples photo session. Snap a keepsake strip together!',
    route: '/games/photobooth',
    accent: '#ff8db3',
    surface: '#351d2a',
    gameType: GameType.PHOTOBOOTH,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 2,
    modes: [{ key: 'online', route: '/games/photobooth' }],
  },
  {
    key: 'uno',
    name: 'UNO',
    mark: '7',
    description: 'The classic card game for 2\u20134. Match, stack, and shout UNO!',
    route: '/games/uno',
    accent: '#f2c94c',
    surface: '#382d16',
    gameType: GameType.UNO,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 4,
    modes: [{ key: 'online', route: '/games/uno' }],
  },
  {
    key: 'tictactoe',
    name: 'Tic Tac Toe',
    mark: 'X',
    description: 'Classic and limited-piece tactical modes, with bots.',
    route: '/games/tictactoe',
    accent: '#d7a7ff',
    surface: '#2c2036',
    gameType: GameType.TICTACTOE,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 2,
    modes: [
      { key: 'online', route: '/games/tictactoe' },
      { key: 'bot', route: '/games/tictactoe/bot' },
    ],
  },
  {
    key: 'connectfour',
    name: 'Connect Four',
    mark: '4',
    description: 'Drop discs, build a line, or challenge a bot.',
    route: '/games/connectfour',
    accent: '#ffcf4a',
    surface: '#26304a',
    gameType: GameType.CONNECTFOUR,
    gameKey: null,
    minPlayers: 2,
    maxPlayers: 2,
    modes: [
      { key: 'online', route: '/games/connectfour' },
      { key: 'bot', route: '/games/connectfour/bot' },
    ],
  },
  {
    key: 'sudoku',
    name: 'Sudoku',
    mark: '9',
    description: 'A focused solo grid with notes and validation.',
    route: '/games/sudoku',
    accent: '#8dd8c1',
    surface: '#1d302d',
    gameType: GameType.SUDOKU,
    gameKey: null,
    minPlayers: 1,
    maxPlayers: 1,
    modes: [{ key: 'solo', route: '/games/sudoku' }],
  },
];

const DISTINCT_PRESENTATION = {
  reversi: {
    name: 'Reversi',
    mark: 'R',
    description: 'Bracket and flip discs across an 8x8 board.',
    accent: '#f4f1e8',
    surface: '#20312a',
  },
  checkers: {
    name: 'Checkers',
    mark: 'C',
    description: 'Force captures, chain jumps, and crown kings.',
    accent: '#ef6a67',
    surface: '#351f21',
  },
  mancala: {
    name: 'Mancala',
    mark: 'M',
    description: 'Sow stones, capture opposites, and fill your store.',
    accent: '#e2b96f',
    surface: '#30291d',
  },
  dotsandboxes: {
    name: 'Dots and Boxes',
    mark: 'D',
    description: 'Draw edges, close boxes, and keep the turn.',
    accent: '#65c9d4',
    surface: '#183036',
  },
  pig: {
    name: 'Pig',
    mark: 'P',
    description: 'Roll for points, hold safely, or risk a bust.',
    accent: '#f09b57',
    surface: '#34251e',
  },
  'grid-salvo': {
    name: 'Grid Salvo',
    mark: 'G',
    description: 'Hide a five-ship fleet, call coordinates, and sink every target.',
    accent: '#58c7d9',
    surface: '#17303a',
  },
  'peg-codebreaker': {
    name: 'Peg Codebreaker',
    mark: '4',
    description: 'Set a private color code or crack it from exact and color clues.',
    accent: '#f3bb52',
    surface: '#332719',
  },
  hangman: {
    name: 'Hangman',
    mark: 'H',
    description: 'Guard a private phrase while the table shares eight misses.',
    accent: '#e9e3ce',
    surface: '#292824',
  },
  'go-fish': {
    name: 'Go Fish',
    mark: 'F',
    description: 'Ask for ranks you hold, draw from the pond, and complete books.',
    accent: '#73d5ae',
    surface: '#18312a',
  },
  'crazy-eights': {
    name: 'Crazy Eights',
    mark: '8',
    description: 'Match rank or suit, steer with eights, and empty your hand first.',
    accent: '#ff7468',
    surface: '#351f21',
  },
  'five-dice-yacht': {
    name: 'Five-Dice Yacht',
    mark: 'Y',
    description: 'Roll three times, hold a combination, and fill thirteen categories.',
    accent: '#f0d567',
    surface: '#30301b',
  },
  'liars-dice': {
    name: "Liar's Dice",
    mark: 'L',
    description: 'Bid across hidden dice, challenge the table, and survive each reveal.',
    accent: '#db8cf0',
    surface: '#302039',
  },
  farkle: {
    name: 'Farkle',
    mark: 'K',
    description: 'Set aside scoring dice, chase hot dice, and bank before a farkle.',
    accent: '#ff9f52',
    surface: '#34251a',
  },
  'shut-the-box': {
    name: 'Shut the Box',
    mark: '9',
    description: 'Roll, close an exact tile sum, and leave the lowest open score.',
    accent: '#d9c39a',
    surface: '#30291e',
  },
  'draw-dominoes': {
    name: 'Draw Dominoes',
    mark: 'D6',
    description: 'Match either open end, draw from the boneyard, and shed every pip.',
    accent: '#f0eee5',
    surface: '#252a2c',
  },
  hearts: {
    name: 'Hearts',
    mark: '\u2665',
    description: 'Pass three, avoid every heart and the queen of spades, or shoot the moon.',
    accent: '#f16b76',
    surface: '#342024',
  },
  spades: {
    name: 'Spades',
    mark: '\u2660',
    description: 'Bid with your partner, manage nils and bags, and make five hundred.',
    accent: '#d8d5ca',
    surface: '#22282a',
  },
  'gin-rummy': {
    name: 'Gin Rummy',
    mark: 'G',
    description: 'Build optimal melds, shed deadwood, and knock before your opponent.',
    accent: '#77cfa8',
    surface: '#193129',
  },
  'card-war': {
    name: 'Card War',
    mark: 'W',
    description: 'Turn over the next cards and let the server resolve every battle and war.',
    accent: '#f0b25d',
    surface: '#34271c',
  },
  'old-maid': {
    name: 'Old Maid',
    mark: 'Q',
    description: 'Draw blind, discard pairs, and avoid the unmatched queen at the end.',
    accent: '#e7a0c4',
    surface: '#34212d',
  },
  hex: {
    name: 'Hex',
    mark: 'H',
    description: 'Build an unbroken route across the eleven-by-eleven hex board.',
    accent: '#6fc6d1',
    surface: '#183038',
  },
  'nine-mens-morris': {
    name: "Nine Men's Morris",
    mark: '9',
    description: 'Place nine stones, close mills, remove rivals, then move or fly.',
    accent: '#d9c18e',
    surface: '#30291d',
  },
  'cee-lo': {
    name: 'Cee-lo',
    mark: '456',
    description: 'Take the banker seat, roll a qualifying hand, and face every challenger.',
    accent: '#f3d45a',
    surface: '#30301b',
  },
  'trivia-quiz-bowl': {
    name: 'Trivia Quiz Bowl',
    mark: '?',
    description: 'Answer ten original questions together and chase the first-correct bonus.',
    accent: '#75b9f0',
    surface: '#1b2d3a',
  },
  'memory-match': {
    name: 'Memory Match',
    mark: 'MM',
    description: 'Reveal one standard field of twelve pairs and keep every match you find.',
    accent: '#f28f62',
    surface: '#35251f',
  },
  'contract-bridge': {
    name: 'Contract Bridge',
    mark: '♠',
    description: 'Auction, declare, defend, and score complete partnership sessions.',
    accent: '#e5c66d',
    surface: '#17352c',
  },
  bourre: {
    name: 'Bourré',
    mark: 'B',
    description: 'Stay or fold, redraw five, then obey strict trump and play-to-win rules.',
    accent: '#f0c96a',
    surface: '#2f291a',
  },
  bluff: {
    name: 'Bluff',
    mark: '!?',
    description: 'Lay cards face down, follow the rank cycle, and decide when to challenge.',
    accent: '#e68aa6',
    surface: '#33212a',
  },
  sevens: {
    name: 'Sevens',
    mark: '7',
    description: 'Open with seven of hearts and build every suit outward from seven.',
    accent: '#75c9a3',
    surface: '#193128',
  },
  'ninety-nine': {
    name: 'Ninety-Nine',
    mark: '99',
    description: 'Manage a running total with reverses, skips, resets, and three lives.',
    accent: '#ee8364',
    surface: '#34231e',
  },
  euchre: {
    name: 'Euchre',
    mark: 'J',
    description: 'Call trump, command both bowers, or go alone for a four-point march.',
    accent: '#e8c663',
    surface: '#2d291a',
  },
  whist: {
    name: 'Whist',
    mark: 'W',
    description: 'Read thirteen quiet tricks with fixed partners and a revealed dealer trump.',
    accent: '#86c5b2',
    surface: '#1b302b',
  },
  'oh-hell': {
    name: 'Oh Hell',
    mark: 'OH',
    description: 'Bid the exact trick count across a complete seven-down-and-up schedule.',
    accent: '#ef8c6d',
    surface: '#34231e',
  },
  president: {
    name: 'President',
    mark: 'P',
    description: 'Climb equal groups, re-enter after passes, finish the order, then trade by rank.',
    accent: '#efcf69',
    surface: '#302a1b',
  },
  slapjack: {
    name: 'Slapjack',
    mark: 'J!',
    description: 'Flip in order, react to every jack, and win the shared pile before it is covered.',
    accent: '#f07b67',
    surface: '#34201d',
  },
  spoons: {
    name: 'Spoons',
    mark: 'S',
    description: 'Pass cards around the table, make four of a kind, and survive the spoon rush.',
    accent: '#d9e2e0',
    surface: '#27302f',
  },
  durak: {
    name: 'Durak',
    mark: 'D',
    description: 'Attack by rank, beat in suit or trump, refill to six, and avoid being the fool.',
    accent: '#d9b55f',
    surface: '#30291b',
  },
  'six-card-golf': {
    name: 'Six-Card Golf',
    mark: 'G6',
    description: 'Swap a hidden two-by-three grid, cancel matching columns, and finish nine low-score holes.',
    accent: '#83c79b',
    surface: '#1d3025',
  },
  'color-match': {
    name: 'Color Match',
    mark: 'CM',
    description: 'Commit three colors in secret, read public targets, and win exact lanes with value.',
    accent: '#f0d765',
    surface: '#2f2c1a',
  },
} as const;

export function getGameCatalog(registry: GameRegistry): GameCatalogEntry[] {
  const distinctGames = registry.getDistinctGames().map((adapter) => {
    const presentation = DISTINCT_PRESENTATION[adapter.key];
    const route = `/games/${adapter.key}`;
    return {
      key: adapter.key,
      ...presentation,
      route,
      gameType: GameType.DISTINCT,
      gameKey: adapter.key,
      minPlayers: adapter.minPlayers,
      maxPlayers: adapter.maxPlayers,
      modes: [{ key: 'online' as const, route }],
    };
  });
  return [...EXISTING_GAMES.map((entry) => ({ ...entry, modes: [...entry.modes] })), ...distinctGames];
}