import type { TriviaQuestion } from '../../../shared';

export const TRIVIA_QUESTION_BANK: readonly TriviaQuestion[] = [
  { prompt: 'Which planet is closest to the Sun?', options: ['Mercury', 'Venus', 'Earth', 'Mars'], correctAnswerIndex: 0 },
  { prompt: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctAnswerIndex: 3 },
  { prompt: 'How many sides does a hexagon have?', options: ['Five', 'Six', 'Seven', 'Eight'], correctAnswerIndex: 1 },
  { prompt: 'Which gas do plants absorb during photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], correctAnswerIndex: 2 },
  { prompt: 'What is the capital of Japan?', options: ['Kyoto', 'Tokyo', 'Osaka', 'Sapporo'], correctAnswerIndex: 1 },
  { prompt: 'Which instrument typically has 88 keys?', options: ['Violin', 'Flute', 'Piano', 'Trumpet'], correctAnswerIndex: 2 },
  { prompt: 'What is water called when it becomes a gas?', options: ['Steam', 'Frost', 'Dew', 'Ice'], correctAnswerIndex: 0 },
  { prompt: 'Which number is a prime?', options: ['21', '27', '29', '33'], correctAnswerIndex: 2 },
  { prompt: 'Which continent contains the Sahara Desert?', options: ['Asia', 'Africa', 'Australia', 'Europe'], correctAnswerIndex: 1 },
  { prompt: 'What force pulls objects toward Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Buoyancy'], correctAnswerIndex: 2 },
  { prompt: 'Which language is primarily spoken in Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Italian'], correctAnswerIndex: 1 },
  { prompt: 'How many minutes are in two hours?', options: ['90', '100', '120', '140'], correctAnswerIndex: 2 },
  { prompt: 'Which organ pumps blood through the body?', options: ['Lung', 'Liver', 'Kidney', 'Heart'], correctAnswerIndex: 3 },
  { prompt: 'What is the freezing point of water in Celsius?', options: ['0', '10', '32', '100'], correctAnswerIndex: 0 },
  { prompt: 'Which animal group does a frog belong to?', options: ['Reptiles', 'Amphibians', 'Mammals', 'Birds'], correctAnswerIndex: 1 },
  { prompt: 'What is the square root of 81?', options: ['7', '8', '9', '10'], correctAnswerIndex: 2 },
  { prompt: 'Which color results from mixing blue and yellow paint?', options: ['Green', 'Orange', 'Purple', 'Brown'], correctAnswerIndex: 0 },
  { prompt: 'Which country is home to the city of Cairo?', options: ['Egypt', 'Greece', 'Turkey', 'Morocco'], correctAnswerIndex: 0 },
  { prompt: 'How many bones are in the adult human body?', options: ['186', '196', '206', '216'], correctAnswerIndex: 2 },
  { prompt: 'Which layer protects Earth from much ultraviolet radiation?', options: ['Mantle', 'Ozone layer', 'Core', 'Troposphere'], correctAnswerIndex: 1 },
  { prompt: 'What is the smallest whole number?', options: ['-1', '0', '1', '10'], correctAnswerIndex: 1 },
  { prompt: 'Which metal is liquid near room temperature?', options: ['Iron', 'Mercury', 'Copper', 'Aluminum'], correctAnswerIndex: 1 },
  { prompt: 'Which direction is opposite east?', options: ['North', 'South', 'West', 'Up'], correctAnswerIndex: 2 },
  { prompt: 'What do bees collect from flowers to make honey?', options: ['Nectar', 'Sand', 'Bark', 'Salt'], correctAnswerIndex: 0 },
  { prompt: 'Which shape has exactly three sides?', options: ['Square', 'Circle', 'Triangle', 'Pentagon'], correctAnswerIndex: 2 },
  { prompt: 'What is the main star in our solar system?', options: ['Polaris', 'Sirius', 'The Sun', 'Vega'], correctAnswerIndex: 2 },
  { prompt: 'Which device measures temperature?', options: ['Barometer', 'Thermometer', 'Compass', 'Altimeter'], correctAnswerIndex: 1 },
  { prompt: 'How many days are in a leap year?', options: ['364', '365', '366', '367'], correctAnswerIndex: 2 },
  { prompt: 'Which part of a plant usually grows underground?', options: ['Flower', 'Leaf', 'Root', 'Fruit'], correctAnswerIndex: 2 },
  { prompt: 'What is 7 multiplied by 8?', options: ['48', '54', '56', '64'], correctAnswerIndex: 2 },
  { prompt: 'Which ocean lies between Africa and Australia?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], correctAnswerIndex: 1 },
  { prompt: 'What is the process of a caterpillar becoming a butterfly?', options: ['Migration', 'Metamorphosis', 'Germination', 'Hibernation'], correctAnswerIndex: 1 },
  { prompt: 'Which punctuation mark ends a direct question?', options: ['Comma', 'Colon', 'Question mark', 'Semicolon'], correctAnswerIndex: 2 },
  { prompt: 'Which simple machine is a ramp?', options: ['Lever', 'Pulley', 'Inclined plane', 'Wheel and axle'], correctAnswerIndex: 2 },
  { prompt: 'Which blood cells primarily carry oxygen?', options: ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'], correctAnswerIndex: 0 },
  { prompt: 'Which fraction equals one half?', options: ['2/3', '3/6', '4/5', '5/8'], correctAnswerIndex: 1 },
  { prompt: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], correctAnswerIndex: 2 },
  { prompt: 'Which natural satellite orbits Earth?', options: ['The Moon', 'Mars', 'Venus', 'Europa'], correctAnswerIndex: 0 },
  { prompt: 'Which material is attracted strongly to a magnet?', options: ['Glass', 'Iron', 'Wood', 'Rubber'], correctAnswerIndex: 1 },
  { prompt: 'How many vertices does a cube have?', options: ['6', '8', '10', '12'], correctAnswerIndex: 1 },
];