/**
 * Centralised UI copy for the Photobooth game. Keeping strings in one place
 * mirrors the pattern used by the chess module and makes future i18n trivial.
 */
export const photoboothStrings = {
  landing: {
    title: 'Photobooth',
    subtitle: 'A cozy little photo session, just for two 💕',
    createLobby: 'Create a room',
    creating: 'Creating…',
    createDescription: 'You pick the frame & theme',
    joinLobby: 'Join your partner',
    joinDescription: 'Enter a 6-digit room code',
    joinModalTitle: 'Join a room',
    joinCodeLabel: 'Room code',
    joinCodePlaceholder: '123456',
    join: 'Join',
    back: '← Back to games',
  },
  setup: {
    chooseStrip: 'Choose your strip',
    stripHint: 'How should your keepsake be arranged?',
    chooseTheme: 'Choose your theme',
    themeHint: 'Pick a vibe — your partner sees it live.',
    patternsThemes: 'Pattern themes',
    simpleThemes: 'Simple themes',
    packsSimple: 'Simple',
    packsPattern: 'Patterns',
    preview: 'Live preview',
    previewHint: 'This is how your photos will sit in the frame.',
    next: 'Next',
    back: 'Back',
    start: 'Start the session ♡',
    waitingTitle: 'Setting the scene…',
    waitingBody: (name: string) => `${name} is picking the perfect frame. Hang tight!`,
    hostBadge: 'You’re the host',
    guestBadge: 'Your partner is choosing',
  },
  capture: {
    round: (n: number, total: number) => `Photo ${n} of ${total}`,
    getReady: 'Get ready…',
    smile: 'Smile! 📸',
    takePhoto: 'Take photo',
    retake: 'Retake',
    continue: 'Continue ♡',
    locked: 'Locked in!',
    waitingPartner: 'Waiting for your partner…',
    partnerReady: 'Your partner is ready 💞',
    partnerCaptured: 'captured their half',
    bothReady: 'Revealing…',
    cameraPrompt: 'Allow camera access to start capturing.',
    cameraDenied:
      'We can’t see your camera. Check your browser permissions and refresh.',
    cameraRetry: 'Enable camera',
    you: 'You',
    partner: 'Partner',
    stripSoFar: 'Your strip so far',
  },
  review: {
    title: 'It’s a wrap! 💕',
    subtitle: 'Style your keepsake and save it forever.',
    filters: 'Filters',
    download: 'Download strip',
    downloadPng: 'PNG',
    downloadPdf: 'PDF',
    saveAs: 'Save your strip',
    preparing: 'Preparing…',
    newSession: 'New session',
    backToLobby: 'Back to lobby',
    made: 'made with love',
  },
  presence: {
    reconnecting: (name: string) => `${name} dropped off — waiting for them to reconnect…`,
  },
  errors: {
    disconnected: 'Reconnecting…',
    loading: 'Loading your photobooth…',
    generic: 'Something went wrong. Please try again.',
  },
} as const;
