import type { DistinctGameKey } from '@/shared';

interface DistinctGameUiDefinition {
  name: string;
  eyebrow: string;
  headline: string;
  description: string;
  accent: string;
  surface: string;
  prompt: string;
}

export const DISTINCT_GAME_UI: Record<DistinctGameKey, DistinctGameUiDefinition> = {
  reversi: {
    name: 'Reversi',
    eyebrow: 'POSITIONAL STRATEGY',
    headline: 'Take the corners. Turn the board.',
    description: 'Bracket opposing discs in any direction, force passes, and own the majority when movement ends.',
    accent: '#f4f1e8',
    surface: '#20312a',
    prompt: 'Choose a highlighted square',
  },
  checkers: {
    name: 'Checkers',
    eyebrow: 'ENGLISH DRAUGHTS',
    headline: 'Read the jump before it lands.',
    description: 'Diagonal movement, mandatory captures, chained jumps, and kings on the far rank.',
    accent: '#ef6a67',
    surface: '#351f21',
    prompt: 'Select a piece, then a legal destination',
  },
  mancala: {
    name: 'Mancala',
    eyebrow: 'KALAH',
    headline: 'Count the landing. Shape the next turn.',
    description: 'Sow counter-clockwise, skip the opposing store, capture across the board, and earn extra turns.',
    accent: '#e2b96f',
    surface: '#30291d',
    prompt: 'Choose one of your active pits',
  },
  dotsandboxes: {
    name: 'Dots and Boxes',
    eyebrow: '4 BY 4 BOXES',
    headline: 'Every harmless line leaves a debt.',
    description: 'Draw one unique edge at a time, close one or two boxes, and keep moving whenever you score.',
    accent: '#65c9d4',
    surface: '#183036',
    prompt: 'Draw an open edge',
  },
  pig: {
    name: 'Pig',
    eyebrow: 'RACE TO 100',
    headline: 'Bank the turn, or press your luck.',
    description: 'Roll a server-generated die, hold to keep the turn total, and avoid the one that wipes it away.',
    accent: '#f09b57',
    surface: '#34251e',
    prompt: 'Roll or hold',
  },
  'grid-salvo': {
    name: 'Grid Salvo',
    eyebrow: '10 BY 10 NAVAL TACTICS',
    headline: 'Hide the fleet. Read the water.',
    description: 'Place five straight ships in private, then trade coordinate shots until one fleet is sunk.',
    accent: '#58c7d9',
    surface: '#17303a',
    prompt: 'Place your fleet or call a coordinate',
  },
  'peg-codebreaker': {
    name: 'Peg Codebreaker',
    eyebrow: 'FOUR-COLOR DEDUCTION',
    headline: 'Every clue narrows the code.',
    description: 'One player sets four private colors. The breaker gets ten guesses with exact and color-only feedback.',
    accent: '#f3bb52',
    surface: '#332719',
    prompt: 'Build a four-color row',
  },
  hangman: {
    name: 'Hangman',
    eyebrow: 'SHARED WORD PUZZLE',
    headline: 'Spend eight misses carefully.',
    description: 'The host guards a phrase while everyone else rotates through letter and full-phrase guesses.',
    accent: '#e9e3ce',
    surface: '#292824',
    prompt: 'Enter a letter or solve the phrase',
  },
  'go-fish': {
    name: 'Go Fish',
    eyebrow: 'THIRTEEN BOOKS',
    headline: 'Ask with a rank in hand.',
    description: 'Collect all four suits of a rank, pull matches across the table, and draw when the answer is no.',
    accent: '#73d5ae',
    surface: '#18312a',
    prompt: 'Choose a player and one of your ranks',
  },
  'crazy-eights': {
    name: 'Crazy Eights',
    eyebrow: 'ORDINARY 52-CARD DECK',
    headline: 'Match the pile. Bend it with an eight.',
    description: 'Follow suit or rank, declare a suit on every eight, and draw only when no card can follow.',
    accent: '#ff7468',
    surface: '#351f21',
    prompt: 'Play a match or draw',
  },
  'five-dice-yacht': {
    name: 'Five-Dice Yacht',
    eyebrow: 'THIRTEEN-ROUND SCORECARD',
    headline: 'Hold the shape. Commit the score.',
    description: 'Use up to three server rolls per turn, preserve chosen dice, and fill each category exactly once.',
    accent: '#f0d567',
    surface: '#30301b',
    prompt: 'Roll, hold dice, then choose a category',
  },
  'liars-dice': {
    name: "Liar's Dice",
    eyebrow: 'HIDDEN DICE AUCTION',
    headline: 'Raise the bid or call the table.',
    description: 'All dice stay private until a challenge. The losing side drops one die and starts the next round.',
    accent: '#db8cf0',
    surface: '#302039',
    prompt: 'Raise quantity or face, or challenge',
  },
  farkle: {
    name: 'Farkle',
    eyebrow: 'RACE TO 10,000',
    headline: 'Keep the scoring dice. Risk the rest.',
    description: 'Select only scoring groups, recycle hot dice, enter with five hundred, and survive the final round.',
    accent: '#ff9f52',
    surface: '#34251a',
    prompt: 'Roll, select scoring dice, or bank',
  },
  'shut-the-box': {
    name: 'Shut the Box',
    eyebrow: 'TILES ONE THROUGH NINE',
    headline: 'Close the exact sum.',
    description: 'Each player works a fresh tile rack until no combination matches the roll. Lowest remainder wins.',
    accent: '#d9c39a',
    surface: '#30291e',
    prompt: 'Roll and close a matching combination',
  },
  'draw-dominoes': {
    name: 'Draw Dominoes',
    eyebrow: 'DOUBLE-SIX DRAW',
    headline: 'Work either open end.',
    description: 'Orient a matching tile on the chain, draw until something fits, and finish before the table blocks.',
    accent: '#f0eee5',
    surface: '#252a2c',
    prompt: 'Play left or right, or draw',
  },
  hearts: {
    name: 'Hearts',
    eyebrow: 'FOUR-PLAYER TRICK AVOIDANCE',
    headline: 'Pass danger. Duck the points.',
    description: 'Follow suit, wait for hearts to break, avoid the queen of spades, and watch for a moon shot.',
    accent: '#f16b76',
    surface: '#342024',
    prompt: 'Pass three cards or play to the trick',
  },
  spades: {
    name: 'Spades',
    eyebrow: 'FIXED PARTNERSHIPS',
    headline: 'Name the contract. Control the trump.',
    description: 'Bid every hand, protect nils, manage bags, and work across the table with your partner.',
    accent: '#d8d5ca',
    surface: '#22282a',
    prompt: 'Bid, then follow suit or cut with spades',
  },
  'gin-rummy': {
    name: 'Gin Rummy',
    eyebrow: 'TWO-PLAYER MELD PLAY',
    headline: 'Shape the hand. Cut the deadwood.',
    description: 'Draw from stock or discard, build optimal runs and sets, then knock at ten or go gin.',
    accent: '#77cfa8',
    surface: '#193129',
    prompt: 'Draw, discard, or knock',
  },
  'card-war': {
    name: 'Card War',
    eyebrow: 'SERVER-DRIVEN BATTLES',
    headline: 'Turn the next card. Settle the war.',
    description: 'Each battle exposes both top cards automatically, including three-down wars on tied ranks.',
    accent: '#f0b25d',
    surface: '#34271c',
    prompt: 'Start the next battle',
  },
  'old-maid': {
    name: 'Old Maid',
    eyebrow: 'HIDDEN-HAND PAIRING',
    headline: 'Draw blind. Leave the queen behind.',
    description: 'Pairs disappear automatically, empty hands rank safe, and the unmatched queen decides last place.',
    accent: '#e7a0c4',
    surface: '#34212d',
    prompt: 'Choose a hidden card position',
  },
  hex: {
    name: 'Hex',
    eyebrow: 'ELEVEN BY ELEVEN',
    headline: 'Build one unbroken crossing.',
    description: 'Vertical connects top to bottom while horizontal connects left to right. Every placement matters.',
    accent: '#6fc6d1',
    surface: '#183038',
    prompt: 'Place a stone on an open hex',
  },
  'nine-mens-morris': {
    name: "Nine Men's Morris",
    eyebrow: 'TWENTY-FOUR NODE STRATEGY',
    headline: 'Close the mill. Open the next one.',
    description: 'Place nine stones, remove after mills, move along the graph, and fly when only three remain.',
    accent: '#d9c18e',
    surface: '#30291d',
    prompt: 'Place, move, or remove a stone',
  },
  'cee-lo': {
    name: 'Cee-lo',
    eyebrow: 'TRADITIONAL BANKER ROUND',
    headline: 'Qualify the roll. Face the table.',
    description: 'The banker sets a three-dice hand, then every challenger rolls for 4-5-6, triples, or a point.',
    accent: '#f3d45a',
    surface: '#30301b',
    prompt: 'Roll a qualifying hand',
  },
  'trivia-quiz-bowl': {
    name: 'Trivia Quiz Bowl',
    eyebrow: 'TEN ORIGINAL QUESTIONS',
    headline: 'Answer together. Reveal together.',
    description: 'Submit one private choice per question, earn ten for correct and five more for the first correct answer.',
    accent: '#75b9f0',
    surface: '#1b2d3a',
    prompt: 'Choose one answer',
  },
  'memory-match': {
    name: 'Memory Match',
    eyebrow: 'TWELVE PAIRS',
    headline: 'Hold the field in your head.',
    description: 'Reveal two tiles, keep the turn on a match, and acknowledge misses before the next search begins.',
    accent: '#f28f62',
    surface: '#35251f',
    prompt: 'Reveal a hidden tile',
  },
  'contract-bridge': {
    name: 'Contract Bridge',
    eyebrow: 'FOUR-SEAT PARTNERSHIP BRIDGE',
    headline: 'Bid the contract. Play both sides of the table.',
    description: 'Complete Rubber, Duplicate, and custom Home sessions with private hands and declarer-controlled dummy.',
    accent: '#e5c66d',
    surface: '#17352c',
    prompt: 'Call, lead, or play the legal card',
  },
  bourre: {
    name: 'Bourré',
    eyebrow: 'STRICT LOUISIANA TRICK PLAY',
    headline: 'Stay only when the five can win.',
    description: 'Redraw, follow suit, trump when void, overtake when possible, and avoid matching the pot with zero tricks.',
    accent: '#f0c96a',
    surface: '#2f291a',
    prompt: 'Stay or fold, then play a required card',
  },
  bluff: {
    name: 'Bluff',
    eyebrow: 'I DOUBT IT',
    headline: 'The rank is fixed. The truth is optional.',
    description: 'Commit one to four cards face down, survive the challenge window, and shed the final claim honestly enough.',
    accent: '#e68aa6',
    surface: '#33212a',
    prompt: 'Make, accept, or challenge the claim',
  },
  sevens: {
    name: 'Sevens',
    eyebrow: 'FAN TAN LAYOUT',
    headline: 'Open the seven. Control both ends.',
    description: 'Start with seven of hearts, open other suits with sevens, and build every row down to ace and up to king.',
    accent: '#75c9a3',
    surface: '#193128',
    prompt: 'Play an adjacent card or pass when blocked',
  },
  'ninety-nine': {
    name: 'Ninety-Nine',
    eyebrow: 'THREE CARDS · THREE TOKENS',
    headline: 'Leave the next player nowhere safe.',
    description: 'Keep the running count at ninety-nine or below with reverses, skips, passes, and chosen ace or ten values.',
    accent: '#ee8364',
    surface: '#34231e',
    prompt: 'Choose a legal card value or concede the hand',
  },
  euchre: {
    name: 'Euchre',
    eyebrow: 'NORTH AMERICAN 24-CARD',
    headline: 'Call the suit. Command the bowers.',
    description: 'Order the upcard or name another trump, choose a lone hand, and race fixed partners to ten.',
    accent: '#e8c663',
    surface: '#2d291a',
    prompt: 'Pass, make trump, discard, or follow effective suit',
  },
  whist: {
    name: 'Whist',
    eyebrow: 'CLASSIC SHORT WHIST',
    headline: 'No auction. Thirteen quiet decisions.',
    description: 'Read the exposed dealer trump, follow suit with your fixed partner, and score every trick beyond six.',
    accent: '#86c5b2',
    surface: '#1b302b',
    prompt: 'Play a legal card to the trick',
  },
  'oh-hell': {
    name: 'Oh Hell',
    eyebrow: 'CONTRACT WHIST · 13 DEALS',
    headline: 'Predict the exact number. No more, no less.',
    description: 'Bid through seven down to one and back, navigate the dealer hook, and earn the ten-point exact bonus.',
    accent: '#ef8c6d',
    surface: '#34231e',
    prompt: 'Bid exactly, then follow suit',
  },
  president: {
    name: 'President',
    eyebrow: 'EIGHT-ROUND CLIMBING',
    headline: 'Match the group. Raise the rank.',
    description: 'Pass and re-enter, finish the full order, then trade the bottom hand’s best card to the president.',
    accent: '#efcf69',
    surface: '#302a1b',
    prompt: 'Lead, climb, pass, or return a card',
  },
  slapjack: {
    name: 'Slapjack',
    eyebrow: 'SERVER-ORDERED REACTION',
    headline: 'Flip cleanly. Hit the jack first.',
    description: 'Play clockwise into one pile, react inside each jack window, and pay a card for every false slap.',
    accent: '#f07b67',
    surface: '#34201d',
    prompt: 'Flip, slap, or close the jack window',
  },
  spoons: {
    name: 'Spoons',
    eyebrow: 'PASS PIPELINE · SPOON RUSH',
    headline: 'Build four. Move before the table does.',
    description: 'Pass one card left through a continuous pipeline, reveal nothing, then race for one fewer spoon.',
    accent: '#d9e2e0',
    surface: '#27302f',
    prompt: 'Pass a card or grab a spoon',
  },
};